import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const inter = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
});

/**
 * Metadata for the ecommerce store.
 * Defines the title, description, and favicon icon.
 *
 * @type {Metadata}
 */
export const metadata: Metadata = {
  title: "Ecommerce Store",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

/**
 * Root layout component for the application.
 *
 * @param {Object} props - Component properties.
 * @param {React.ReactNode} props.children - The child components to be wrapped by the layout.
 *
 * @returns - The root layout containing global styles and fonts.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "bg-[linear-gradient(to_bottom_right,#000000,#434343)] min-h-screen font-sans antialiased",
          inter.variable
        )}
      >
        {children}
      </body>
    </html>
  );
}
